### ISSUE TITLE
Child-Bridge restarts when trigger conditions met

### ISSUE THREAD

**Issue by wuedan** [zerwuff/homebridge-alphaess#2]
**Describe The Bug:**
Plugin restarting when trigger triggered

**To Reproduce:**
Conditions for trigger have been met, automation started in HomeKit, at the same time child-bridge restarted

**Expected behavior:**
The child-bridge not to be restarted.

**Logs:**

```
(typeerror: Cannot read properties of null (reading 'Time')    at AlphaImageService.renderImage (/usr/local/lib/node_modules/homebridge-alphaess/src/alpha/AlphaImageService.ts:119:21)    at /usr/local/lib/node_modules/homebridge-alphaess/src/AlphaPlugin.ts:98:36    at processTicksAndRejections (node:internal/process/task_queues:96:5)[4/19/2023, 12:47:26 PM] [homebridge-alphaess] Child bridge process ended[4/19/2023, 12:47:26 PM] [homebridge-alphaess] Process Ended. Code: 1, Signal: null[4/19/2023, 12:47:33 PM][homebridge-alphaess] Restarting Process...[4/19/2023, 12:47:33 PM] [homebridge-alphaess] Launched child bridge with PID 13238[4/19/2023, 12:47:33 PM] Registering platform 'homebridge-alphaess.AlphaEssPlatform'[4/19/2023, 12:47:33 PM] 
[homebridge-alphaess] Loaded homebridge-alphaess v2.24.0 child bridge successfully[4/19/2023, 12:47:33 PM] Loaded 0 cached accessories from cachedAccessories.0E8B0523A971.[4/19/2023, 12:47:33 PM] 
[homebridge-alphaess] Alpha Ess Platform Plugin started [4/19/2023, 12:47:33 PM] Initializing platform accessory 'AlphaEssBattery'...[4/19/2023, 12:47:33 PM] Initializing platform accessory 'AlphaEssTrigger'...[4/19/2023, 12:47:33 PM] Homebridge v1.6.0 (HAP v0.11.0) (homebridge-alphaess) is running on port 57446.2023-04-19 12:47:36.451 node[13238:4780352] XType: failed to connect - Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process.}2023-04-19 12:47:36.451 node[13238:4780352] Font server protocol version mismatch (expected:5 got:0), falling back to local fonts2023-04-19 12:47:36.451 node[13238:4780352] XType: unable to make a connection to the font daemon!2023-04-19 12:47:36.451 node[13238:4780352] XType: XTFontStaticRegistry is enabled as fontd is not available.)
```

**Plugin Config:**

```json
{
            "username": "xxxxxxx",
            "password": "xxxxxxx",
            "serialnumber": "xxxxxxx",
            "powerLoadingThreshold": 3000,
            "socLoadingThreshold": 100,
            "refreshTimerInterval": 60000,
            "power_image_filename": "/tmp/alpha_power_image.png",
            "logrequestdata": false,
            "_bridge": {
                "username": "0E:8B:05:23:A9:71",
                "port": 57446
            },
            "platform": "AlphaEssPlatform"
        }
```

**Screenshots:**
<img width="657" alt="Screenshot 2023-04-19 12-56-30" src="https://user-images.githubusercontent.com/79700665/233054309-f7c6fc13-428c-4287-93e0-697cd851c9e3.png">

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: v1.6.0
* **Node.js Version**: v16.14.2
* **NPM Version**: ?
* **Operating System**: macOS Ventura

**Comment by zerwuff** [comment]
Should be fixed with 2.25.0. Please check and let me know if this version looks good for you. 

If not, i need to look more deeply into it. It would be helpful if you provide the console output from the alpha plugin in Homebridge *DEBUG* mode. 
This also shows you when the trigger is met.
Thanks for not submitting too sensitive information. BR, Jens

**Comment by wuedan** [comment]
Thank you for the swift action! I just installed the update and will monitor
As a side note, there is still the font-error when restarting home bridge and loading the plugin, I assume this has no influence on the actual issue reported, but just wanted to let you know. 

`2023-04-19 15:49:23.420 node[22011:4852820] XType: failed to connect - Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process.}
2023-04-19 15:49:23.420 node[22011:4852820] Font server protocol version mismatch (expected:5 got:0), falling back to local fonts
2023-04-19 15:49:23.420 node[22011:4852820] XType: unable to make a connection to the font daemon!
2023-04-19 15:49:23.420 node[22011:4852820] XType: XTFontStaticRegistry is enabled as fontd is not available.`

**Comment by zerwuff** [comment]
I have seen this. 
Can you check if the image rendering  is working on your machine by just using the property               *"power_image_filename": "/tmp/alpha_power_image.png"* in the configuration  ?
Seems an issue with mac os ventura + font rendering. 
If no image is rendered at all, i need to further investigate this on a mac.

**Comment by wuedan** [comment]
It is still restarting and also the trigger did not fire in HomeKit yesterday in the late afternoon (I have set HomeKit to send me a notification when the trigger triggers)
Let me know if this is enough extract from the log (I copy/pasted it here but it was not formatted very well and therefore hard to read)

<img width="590" alt="Screenshot 2023-04-20 07-48-51(1)" src="https://user-images.githubusercontent.com/79700665/233270108-41133c81-0a65-4bfb-904f-ed9adf6e33b8.png">

**Comment by zerwuff** [comment]
hmm, seems like the patch was not applied on your homebridge installation. maybe the old version is still cached.
 please try the following:
 go to plugins, search for the alpha-ess homebridge plugin, click on update latest version, check that the most recent version 2.26.0 is installed or if not update it- wait for the outcome of the installation which could take some time. 
now restart the homebridge via the on/off button on the top right, then the plugin is forced to be reloaded reloaded.

additionally, i updated the plugin with a additional check, please let me know if the error still exists

**Comment by wuedan** [comment]
Thanks again for looking into this, really appreciate it! If you accept donations via PayPal etc. please feel free to share.

Updated successfully to 2.26.0 

<img width="440" alt="Screenshot 2023-04-20 09-43-30" src="https://user-images.githubusercontent.com/79700665/233295934-8f653633-2c84-4296-8423-1e240b11f4e1.png">

Restarted Homebridge but issue persists as seen in the logs:

`typeerror: Cannot read properties of null (reading 'Time')    at AlphaImageService.renderImage (/usr/local/lib/node_modules/homebridge-alphaess/src/alpha/AlphaImageService.ts:115:86)    at /usr/local/lib/node_modules/homebridge-alphaess/src/AlphaPlugin.ts:99:38    at processTicksAndRejections (node:internal/process/task_queues:96:5)[4/20/2023, 9:40:59 AM] [homebridge-alphaess] Child bridge process ended[4/20/2023, 9:40:59 AM] [homebridge-alphaess] Process Ended. Code: 1, Signal: null[4/20/2023, 9:41:06 AM] [homebridge-alphaess] Restarting Process...`

**Comment by zerwuff** [comment]
thanks for testing again. it seems the response from alpha is incomplete. i did a new release (2.2.27) including the following:
* added better check for the alpha response. your image processing wont work currently.
* added response logging from statistics  (only in debug mode!) for me to further investigate 

It would be greatly helpful if you could provide the response of the ' [homebridge-alphaess] Response from statistics data :' log line that will show up in debug mode. I can use this for further analysis. It seems that some of the time data is not included in the alpha response.
Debug mode is set in the homebridge settings: 
<img width="2981" alt="Img" src="https://user-images.githubusercontent.com/120713107/233341439-d50ece44-4b3a-42f9-b71a-e67cd36bbb1a.png">

Please attach the the data list  {"code":200,"info":"Success"...  to the ticket  i can further investigate. This should be not to personalized and include only power information for today.

Thanks for your support and feedback. If this bug is resolved and you are happy, you are free to send donations via https://www.paypal.com/paypalme/jenshalde

**Comment by wuedan** [comment]
Update is installed, statistics data attached as text-file.
Font error message still persists, I'll keep you posted about any potential further crashes of the plugin.

[statistics_data.txt](https://github.com/zerwuff/homebridge-alphaess/files/11285233/statistics_data.txt)

Thank you!

**Comment by zerwuff** [comment]
thanks for the update, this helped further bugfixing and providing a new version.

can you check if the image is beeing rendered with the version 2.28 on mac ?  it looks like node.js is using local local fonts instead of the mac rendering service which should be fine.  if yes, i'd like to close the bug.

**Comment by wuedan** [comment]
Sorry, for just getting back to you now.
Where should I see the rendered picture, actually? I never saw one and when I start up home bridge, I continue to get the error message:
`2023-05-04 09:19:56.576 node[13903:1017395] XType: failed to connect - Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process.}
2023-05-04 09:19:56.576 node[13903:1017395] Font server protocol version mismatch (expected:5 got:0), falling back to local fonts
2023-05-04 09:19:56.576 node[13903:1017395] XType: unable to make a connection to the font daemon!
2023-05-04 09:19:56.577 node[13903:1017395] XType: XTFontStaticRegistry is enabled as fontd is not available.`

**Comment by zerwuff** [comment]
To enable image rendering, add the following settings key to the configuration:
`
"power_image_filename":"/tmp/somefilename.png", 
`     
More details : https://github.com/zerwuff/homebridge-alphaess#configuration
The rendering is triggered within the `refreshTimerInterval`. If the rendering succeeds, an image will be saved onto that location.  I use this to show this on my home screen with the homebridge camera plugin.
If not, the rendering seems to be broken - your error indicated that somehow.

For a solution of the error msg - not running font daemon on mac os - please see: https://stackoverflow.com/questions/69986582/the-connection-to-service-named-com-apple-fonts-was-invalidated-on-xcodebuild-r 
and leave me a feedback if this solves your problem after you started the font daemon.

Whats the overall behaviour besides that - is the homebridge still restarting after the error message ? Does the trigger work ? Or is this "just" a rendering problem

**Comment by wuedan** [comment]
With that command in the Mac Terminal I got rid of the error message and an image is generated in the temp folder!
`sudo launchctl load -w /System/Library/LaunchAgents/com.apple.fontd.useragent.plist`

The child-bridge doesn't seem to be restarting anymore, I am now waiting for the battery to get to 100% to see if the trigger fires, Will update this thread after some more tests.

**Comment by zerwuff** [comment]
Nice, thanks for the update & further testing. Hope we can close the issue if the trigger is working as expected.

**Comment by wuedan** [comment]
I am getting some 
<img width="166" alt="image" src="https://user-images.githubusercontent.com/79700665/236472849-86a4714f-5544-4c75-bf31-f11d27692005.png">
in the console (I have debug turned off right now) but otherwise It seems to be working at this point!
I assume these messages come from a timeout with the server or something like that?

Thank you so much for your help and patience resolving this issue!

**Comment by zerwuff** [comment]
Exactly, this error indicates empty responses from the alpha backend. But since the rendering works this is an temporary issue on some of the backend responses. I havent seen this issues on my account. Are you using a Proxy?

**Comment by wuedan** [comment]
I don't know, but I just got new error messages.
I don't use a proxy and my connection actually is pretty stable - I do video calls all day and it never lags or freezes..

<img width="890" alt="image" src="https://user-images.githubusercontent.com/79700665/237046776-978f3d16-eb0f-4580-8043-0b6a88c2b314.png">

**Comment by zerwuff** [comment]
Fix is provided within homebridge-alphaess@2.31.0 which makes network issues like that more stable
