### ISSUE TITLE
not able to fetch trigger

### ISSUE THREAD

**Issue by akassa89** [zerwuff/homebridge-alphaess#7]
Hi there!

I'm trying to connect my AlphaESS to HomeKit, but the camera pictures with the charts are missing.
![image](https://github.com/zerwuff/homebridge-alphaess/assets/148866909/cc6dd0e3-84a8-4565-854f-508a68314db4)
The logs only shows me this: [homebridge-alphaess] could not fetch trigger result 

[12/31/2023, 2:06:01 PM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge FA6A) is running on port 51671.
[12/31/2023, 2:06:02 PM] [homebridge-alphaess] Launched child bridge with PID 15996
[12/31/2023, 2:06:04 PM] Registering platform 'homebridge-alphaess.AlphaEssPlatform'
[12/31/2023, 2:06:04 PM] [homebridge-alphaess] Loaded homebridge-alphaess v2.71.0 child bridge successfully
[12/31/2023, 2:06:04 PM] Loaded 0 cached accessories from cachedAccessories.0E0531B4E13A.
[12/31/2023, 2:06:04 PM] [homebridge-alphaess] Alpha Ess Platform Plugin started 
[12/31/2023, 2:06:05 PM] Initializing platform accessory 'AlphaEssBattery'...
[12/31/2023, 2:06:05 PM] Initializing platform accessory 'EnergyTriggerPlugin'...
[12/31/2023, 2:06:05 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-alphaess) is running on port 58774.
[12/31/2023, 2:06:06 PM] [homebridge-alphaess] could not fetch trigger result 

Thanks in advanced for your help!

**Comment by zerwuff** [comment]
Hi, thanks for using the plugin.  The charts are showing up as a camera on your home app (and actually *not* in the hombridge app). 
The Alphaess plugin will render the images, the Camera FFMPeg Plugin will stream it to your home app on your apple devices.
All you need to do is to to install the Camera FFMpeg Plugin to your homebridge instance and add the plattform section (where already your alpha ess plugin config is) with the following config for the camera plugin :


```
 "platforms": [
 // alpha ess plugin config with image locations at /tmp/alpha_power_image.png and /tmp/tibber_image.png
 // 
, 
 {
            "name": "Camera FFmpeg",
            "videoProcessor": "/usr/bin/ffmpeg",
            "cameras": [
                {
                    "name": "AlphaESS",
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-f image2 -loop 1 -s 640x360 -pix_fmt yuvj422p -i /tmp/alpha_power_image.png",
                        "stillImageSource": "-i file:///tmp/alpha_power_image.png",
                        "audio": false
                    }
                },
                {
                    "name": "Trigger",
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-f image2 -loop 1 -s 640x360 -pix_fmt yuvj422p -i /tmp/tibber_image.png",
                        "stillImageSource": "-i file:///tmp/tibber_image.png",
                        "audio": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
]
```

Note: you can omit the second image (everything in the "Trigger" block) if you are not interested on the trigger status of the alpha ess plugin.  

Please let me know if this works or not  - if so, you can close the ticket.

**Comment by akassa89** [comment]
Hi @zerwuff, 
the plugin *Camera FFmpeg* was part of the missing key. But now there are other problems:

`[[1/1/2024, 8:39:20 AM] [homebridge-alphaess] undefined`
`[1/1/2024, 8:39:20 AM] [homebridge-alphaess] Getting Detail Data from Alpha Ess failed`
`[1/1/2024, 8:39:27 AM] [homebridge-alphaess] could not fetch trigger result`
`[1/1/2024, 8:39:31 AM] [homebridge-alphaess] Getting Statistics Data from Alpha Ess failed undefined`
`[1/1/2024, 8:40:28 AM] [homebridge-alphaess] undefined`
`[1/1/2024, 8:40:28 AM] [homebridge-alphaess] Getting Detail Data from Alpha Ess failed`
`[1/1/2024, 8:40:28 AM] [homebridge-alphaess] Getting Statistics Data from Alpha Ess failed undefined`
`[1/1/2024, 8:40:28 AM] [homebridge-alphaess] could not fetch trigger result`
`[1/1/2024, 8:41:25 AM] [Homebridge UI] Terminal session ended.`
`[1/1/2024, 8:41:29 AM] [homebridge-alphaess] could not fetch trigger result`
`[1/1/2024, 8:41:30 AM] [homebridge-alphaess] Getting Statistics Data from Alpha Ess failed undefined`
`[1/1/2024, 8:41:55 AM] [homebridge-alphaess] <html>`
`<head><title>500 Internal Server Error</title></head>`
`<body>`
`<center><h1>500 Internal Server Error</h1></center>`
`<hr><center>nginx/1.20.1</center>`
`</body>`
`</html>`
Thais is my AlphaESS plugin config:
`‚{`
            `"alphaUrl": "https://openapi.alphaess.com/api",`
            `"appid": "alpha1e245db72d3059d6",`
           ` "appsecret": "#####",`
           ` "serialnumber": "######",`
            `"powerLoadingThreshold": 1500,`
            `"socLoadingThreshold": 50,`
            `"refreshTimerInterval": 60000,`
           ` "power_image_filename": "/tmp/alpha_power_image.png",`
           ` "logrequestdata": false,`
           ` "tibberEnabled": true,`
           ` "tibberUrl": "https://api.tibber.com/v1-beta/gql",`
           ` "tibberAPIKey": "######",`
           ` "tibberHomeId": "######",`
           ` "tibberLoadBatteryEnabled": false,`
           ` "tibberLoadingMinutes": 60,`
           ` "tibberThresholdSOC": 60,`
           ` "tibberThresholdEur": 0.01,`
           ` "triggerImageFilename": "/tmp/tibber_image.png",`
           ` "_bridge": {`
           `     "username": "######",`
           `     "port": 58774`
          `  },`
          `  "platform": "AlphaEssPlatform"`
       ` },
`

and this is the Camera FFmpeg config:
`
‚{
            "name": "Camera FFmpeg",
            "videoProcessor": "/usr/bin/ffmpeg",
            "cameras": [
                {
                    "name": "AlphaESS",
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-f image2 -loop 1 -s 640x360 -pix_fmt yuvj422p -i /tmp/alpha_power_image.png",
                        "stillImageSource": "-i file:///tmp/alpha_power_image.png",
                        "audio": false
                    }
                },
                {
                    "name": "Trigger",
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-f image2 -loop 1 -s 640x360 -pix_fmt yuvj422p -i /tmp/tibber_image.png",
                        "stillImageSource": "-i file:///tmp/tibber_image.png",
                        "audio": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
`

result:
![B1665610-C0C0-4865-A464-2D120D97AFF5](https://github.com/zerwuff/homebridge-alphaess/assets/148866909/020483ba-a45a-4c62-aa76-e2d9c3c18f6b)

thx for your help

**Comment by zerwuff** [comment]
hi, it seems like alpha backend servers are having trouble, therefore the server error is thrown, no image rendering is done.
see https://github.com/alphaess-developer/alphacloud_open_api/issues/57

im having this on my setup also. i hope its getting fixed by alpha soon.

**Comment by akassa89** [comment]
Hi,
after all i still get this status:
`[1/3/2024, 8:22:42 AM] [homebridge-alphaess] could not fetch trigger result`
This is not a big amount of information... where i can change the debug level for the alpha plugin? 
Or i need to debug via Homebridge? And in the end which level we need? 

Thanks for your help!

**Comment by zerwuff** [comment]
Hi, debug mode is enabled via Homebridge Debug Mode -D (enabled) in the homebridge settings. 

Also, enable  "logrequestdata": true in the alpha ess plugin to see which requests are failing. 
I have set a higher "refreshTimerInterval"  to prevent alpha backend from blocking too high request rate. 
Try 300000 (5mins) that should be enough.
Restart the homebridge after all is set to see the debug log.

**Comment by akassa89** [comment]
Logs:
`[1/3/2024, 10:58:56 AM] [homebridge-alphaess] Restarting Process...`
`[1/3/2024, 10:58:57 AM] [homebridge-alphaess] Launched child bridge with PID 5638`
`[1/3/2024, 10:58:58 AM] Registering platform 'homebridge-alphaess.AlphaEssPlatform'`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] Loaded homebridge-alphaess v2.71.0 child bridge successfully` 
`[1/3/2024, 10:58:58 AM] Loaded 0 cached accessories from cachedAccessories.0E0531B4E13A.`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] Alpha Ess Platform Plugin started`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] Alpha ESS Accessory Loaded`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] fetch Alpha ESS Data -> fetch token`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] Log Request data for url https://openapi.alphaess.com/api/getLastPowerData?sysSn=ALB002022110785`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] authtimestamp     1704275939`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] data`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] authsignature:##############`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] token:`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] serialNumber:###########`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] ###################`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] Rendering Image`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] mqtt_url is not set, not pushing anywhere`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] EnergyTriggerPlugin plugin loaded`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] ###############`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] Tibber API trigger is enabled`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] calculateAlphaTrigger called.`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] Log Request data for url https://openapi.alphaess.com/api/getLastPowerData?sysSn=ALB002022110785`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] authtimestamp     1704275939`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] data`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] authsignature:############`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] token:`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] serialNumber:ALB002022110785`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] ###################`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] mqtt_url is not set, not pushing anywhere`
`[1/3/2024, 10:58:59 AM] Initializing platform accessory 'AlphaEssBattery'...`
`[1/3/2024, 10:58:59 AM] Initializing platform accessory 'EnergyTriggerPlugin'...`
`[1/3/2024, 10:58:59 AM] Publishing bridge accessory (name: homebridge-alphaess, publishInfo: {`
`  username: '##:##:##:##:##:##',`
`  port: 58774,`
`  pincode: '***-**-***',`
`  category: 2,`
`  bind: [ 'br3', [length]: 1 ],`
`  mdns: undefined,`
`  addIdentifyingMaterial: true,`
`  advertiser: 'bonjour-hap'
}).`
`[1/3/2024, 10:58:59 AM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-alphaess) is running on port 58774.`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] Could not fetch todays prices, error :  TypeError: prices.forEach is not a function`
`    at TibberService.findLowestPrice (/homebridge/node_modules/homebridge-alphaess/src/tibber/TibberService.ts:76:12)`
`    at /homebridge/node_modules/homebridge-alphaess/src/tibber/TibberService.ts:122:43`
`    at processTicksAndRejections (node:internal/process/task_queues:95:5)`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] could not fetch trigger result`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] SOC: 5.2`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] SOC: 5.2`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] soc: 5.2`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] pBatt :-76`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] stringPowerTotal :678`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] Calculating trigger ->  powerLoadingThreshold: 1500 socLoadingThreshold:50 resulting in trigger:false`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] Trigger: alpha ess: false tibber: false total:false`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] Triggered GET ContactSensorState`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] trigger not fired -> status CONTACT_DETECTED`

**Comment by akassa89** [comment]
Logs:
`[1/3/2024, 10:58:56 AM] [homebridge-alphaess] Restarting Process...`
`[1/3/2024, 10:58:57 AM] [homebridge-alphaess] Launched child bridge with PID 5638`
`[1/3/2024, 10:58:58 AM] Registering platform 'homebridge-alphaess.AlphaEssPlatform'`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] Loaded homebridge-alphaess v2.71.0 child bridge successfully` 
`[1/3/2024, 10:58:58 AM] Loaded 0 cached accessories from cachedAccessories.0E0531B4E13A.`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] Alpha Ess Platform Plugin started`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] Alpha ESS Accessory Loaded`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] fetch Alpha ESS Data -> fetch token`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] Log Request data for url https://openapi.alphaess.com/api/getLastPowerData?sysSn=#######`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] authtimestamp     1704275939`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] data`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] authsignature:##############`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] token:`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] serialNumber:###########`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] ###################`
`[1/3/2024, 10:58:58 AM] [homebridge-alphaess] Rendering Image`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] mqtt_url is not set, not pushing anywhere`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] EnergyTriggerPlugin plugin loaded`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] ###############`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] Tibber API trigger is enabled`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] calculateAlphaTrigger called.`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] Log Request data for url https://openapi.alphaess.com/api/getLastPowerData?sysSn=############`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] authtimestamp     1704275939`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] data`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] authsignature:############`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] token:`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] serialNumber:############`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] ###################`
`[1/3/2024, 10:58:59 AM] [homebridge-alphaess] mqtt_url is not set, not pushing anywhere`
`[1/3/2024, 10:58:59 AM] Initializing platform accessory 'AlphaEssBattery'...`
`[1/3/2024, 10:58:59 AM] Initializing platform accessory 'EnergyTriggerPlugin'...`
`[1/3/2024, 10:58:59 AM] Publishing bridge accessory (name: homebridge-alphaess, publishInfo: {`
`  username: '##:##:##:##:##:##',`
`  port: 58774,`
`  pincode: '***-**-***',`
`  category: 2,`
`  bind: [ 'br3', [length]: 1 ],`
`  mdns: undefined,`
`  addIdentifyingMaterial: true,`
`  advertiser: 'bonjour-hap'
}).`
`[1/3/2024, 10:58:59 AM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-alphaess) is running on port 58774.`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] Could not fetch todays prices, error :  TypeError: prices.forEach is not a function`
`    at TibberService.findLowestPrice (/homebridge/node_modules/homebridge-alphaess/src/tibber/TibberService.ts:76:12)`
`    at /homebridge/node_modules/homebridge-alphaess/src/tibber/TibberService.ts:122:43`
`    at processTicksAndRejections (node:internal/process/task_queues:95:5)`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] could not fetch trigger result`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] SOC: 5.2`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] SOC: 5.2`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] soc: 5.2`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] pBatt :-76`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] stringPowerTotal :678`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] Calculating trigger ->  powerLoadingThreshold: 1500 socLoadingThreshold:50 resulting in trigger:false`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] Trigger: alpha ess: false tibber: false total:false`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] Triggered GET ContactSensorState`
`[1/3/2024, 10:59:00 AM] [homebridge-alphaess] trigger not fired -> status CONTACT_DETECTED`

**Comment by zerwuff** [comment]
hmm, there seems to be problems with the tibber api now :( i added some more logging, please update the alpha ess plugin.
on my config, I did let the tibber home api empty, please try to remove this completly from the settings via config editor. 
btw, it takes some time to render & calculate the trigger after the interval is set up to a higher cadence like 5 minutes

**Comment by akassa89** [comment]
This came up directly after restarting the sub-bridge:
`[1/3/2024, 12:55:19 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-alphaess) is running on port 58774.`
`[1/3/2024, 12:55:20 PM] [homebridge-alphaess] SOC: 22`
`[1/3/2024, 12:55:21 PM] [homebridge-alphaess] Trigger: alpha ess: false tibber: false total:false`
`[1/3/2024, 12:55:21 PM] [homebridge-alphaess] Triggered GET ContactSensorState`
`[1/3/2024, 12:55:21 PM] [homebridge-alphaess] trigger not fired -> status CONTACT_DETECTED`
`[1/3/2024, 12:55:21 PM] [homebridge-alphaess] SOC: 22`
`[1/3/2024, 12:55:21 PM] [homebridge-alphaess] soc: 22`
`[1/3/2024, 12:55:21 PM] [homebridge-alphaess] pBatt :0`
`[1/3/2024, 12:55:21 PM] [homebridge-alphaess] stringPowerTotal :606`
`[1/3/2024, 12:55:21 PM] [homebridge-alphaess] Calculating trigger ->  powerLoadingThreshold: 1500 socLoadingThreshold:50 resulting in trigger:false`
`[1/3/2024, 12:57:09 PM] [Camera FFmpeg] [AlphaESS] Snapshot requested: 1280 x 720`
`[1/3/2024, 12:57:09 PM] [Camera FFmpeg] [AlphaESS] Snapshot command: /usr/bin/ffmpeg -i file:///tmp/alpha_power_image.png -frames:v 1 -f image2 - -hide_banner -loglevel error`
`[1/3/2024, 12:57:09 PM] [Camera FFmpeg] [AlphaESS] FFmpeg process creation failed: spawn /usr/bin/ffmpeg ENOENT`
`[AlphaESS] Snapshot request handler provided empty image buffer!`

and after 30 minutes waiting: same error
`[1/3/2024, 1:30:43 PM] [Camera FFmpeg] [Trigger] FFmpeg process creation failed: spawn /usr/bin/ffmpeg ENOENT`

**Comment by zerwuff** [comment]
hmm, this indicates an ffmpeg problem - > 

in  plattforms change the videoprocessor to **/usr/local/bin/ffmpeg** (+local in the path), my setup uses a different mpeg installation.
[...

{
             "videoProcessor": "/usr/local/bin/ffmpeg",
}
]

**Comment by akassa89** [comment]
amazing… it works!
thank you 

But the value in the chart is not correct. 
![IMG_7358](https://github.com/zerwuff/homebridge-alphaess/assets/148866909/8029e192-db29-4e84-863f-8a482216c141)

do you think it takes some time to render the correct data?

**Comment by akassa89** [comment]
Right in this moment it came up:
![IMG_7359](https://github.com/zerwuff/homebridge-alphaess/assets/148866909/a4b25c4c-2ebc-4eb0-b99d-f99972be9940)

BEST SUPPORT EVER 😉

**Comment by zerwuff** [comment]
hi, yes. it does :) please be patient. glad you manage it. the left chart will draw on the fly, i.e it can just record the current status of your system and will draw it there.  
please not, tibber and loading with tibber is under heavy deveopment - ie it should work (i use it on my own), but will only *once* a day set or unset the best loading time to fill your batteries. 
if you have more issues, please let me know.
